DATASET:
  FILENAME: "ds2.bin"
  DTYPE: int16
  PRN_ID_TO_SEARCH: 6

RF_FRONT_END:
  FS: 16368000.0
  FIF: 4130900.0

GPS_STANDARD:
  PRN_CHIP_RATE: 1023000.0
  PRN_LENGTH: 1023

ACQUISITION:
  DOPPLER_RANGE: 10000
  DOPPLER_STEP: 500
  TIME_TO_PROCESS: 0.001