DATASET:
  FILENAME: "TGS_L1_E1.dat"
  DTYPE: int8

RF_FRONT_END:
  FS: 26000000.0
  FC: 6390000.0

GPS_STANDARD:
  PRN_CHIP_RATE: 1023000.0
  PRN_LENGTH: 1023

ACQUISITION:
  DOPPLER_RANGE: 5000
  DOPPLER_STEP: 500
  TIME_TO_PROCESS: 0.5