DATASET:
  FILENAME: "OSNMA_cleandata_opensky_460s.dat"
  DTYPE: int8
  PRN_ID_TO_SEARCH: 5

RF_FRONT_END:
  FS: 26000000.0
  FIF: 1569030000.0

GPS_STANDARD:
  PRN_CHIP_RATE: 1023000.0
  PRN_LENGTH: 1023

ACQUISITION:
  DOPPLER_RANGE: 10000
  DOPPLER_STEP: 500
  TIME_TO_PROCESS: 0.001